image: openjdk:8-jdk

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - mkdir android-sdk-linux/licenses
  - printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > android-sdk-linux/licenses/android-sdk-license
  - printf "84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk-linux/licenses/android-sdk-preview-license
  - android-sdk-linux/tools/bin/sdkmanager --update > update.log
  - android-sdk-linux/tools/bin/sdkmanager "platforms;android-26" "build-tools;24.0.0" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - cd juggernaul
  - chmod +x ./gradlew

stages:
  - build
  - release

build:
  stage: build
  except:
    refs:
      - release
  script:
    - ./gradlew assembleDebug

release:
  only:
    refs:
      - release
  stage: release
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - juggernaul/app/build/outputs/

